### ISSUE TITLE
无法返回openai信息

### ISSUE THREAD

**Issue by dikayyy** [bh1xaq/ChatGPT-zabbixAlart#1]
Problem: CPU资源IDLE持续10分钟少于15% - 当前值: 1.77 %
故障: CPU资源IDLE持续10分钟少于15% - 当前值: 1.77 %
ID: 1619863723
时间: 2023.02.16 14:14:13
主机: 172.16.14.6 
级别: High

 --- 
 OpenAI 砖家建议：
 [object Object]

**Comment by suyajun002** [comment]
测试的时候也是无法返回openai信息

故障：Lack of available memory (<20M of 682.66 MB)
这是一条测试告警信息。
 --- 
 OpenAI 砖家建议：
 [object Object]

**Comment by bh1xaq** [comment]
您好，问题已经修复，您可以重新尝试一下。
