### ISSUE TITLE
测试的时候砖家建议 是 [object Object]

### ISSUE THREAD

**Issue by suyajun002** [bh1xaq/ChatGPT-zabbixAlart#2]
故障：Lack of available memory (<20M of 682.66 MB)
这是一条测试告警信息。
 --- 
 OpenAI 砖家建议：
 [object Object]

**Comment by bh1xaq** [comment]
您好，我在这个issue #3 中修复了这个问题，您可以再试一下。

**Comment by suyajun002** [comment]
测试已经成功

故障: Zabbix agent is not available (for 3m)
Zabbix agent is not available (for 3m)
 --- 
 OpenAI 砖家建议：
 1、检查监控服务器上的 zabbix agent 进程状态，确保其处于运行状态。

2、检查监控服务器上 zabbix agent 进程的日志，找出可能的异常原因。

3、如果找不到异常原因，则可以通过重启 zabbix agent 来尝试解决该问题。

**Comment by bh1xaq** [comment]
好的，那我就关掉这个issues了。
