### ISSUE TITLE
发出来的告警  【OpenAI 砖家建议：】没有得到想要的答案

### ISSUE THREAD

**Issue by suyajun002** [bh1xaq/ChatGPT-zabbixAlart#4]
发出来的告警  【OpenAI 砖家建议：】没有得到想要的答案
感觉是把 所有的告警信息 发给api了
应该截取一下只发送(故障: High memory utilization ( >90% for 5m))这一条。

告警
故障: High memory utilization ( >90% for 5m)
触发时间：2023.02.22 11:52:23
主机名称：**************

 --- 
 OpenAI 砖家建议：
 1.首先，根据Zabbix告警消息中提示的内容和关键字，对系统中出现的问题进行定位，尝试排查出问题所在；

2.如果无法查明原因，需要根据Zabbix告警消息中提示的信息，进行远程支持，以了解更多信息；

3.根据告警信息进行故障排查，尝试解决出现的问题；

4.如果解决不了，可以考虑重新部署系统；

5.最后，根据Zabbix告警反馈情况，排查并及时记录系统中发生的问题，以便进行后续分析。

**Comment by bh1xaq** [comment]
您好，向OpenAI请求的内容只包含告警的Subject。
受限于上游OpenAI的能力，确实建议的内容仅供参考，还需要运维工程师进行判断。

**Comment by suyajun002** [comment]
明白了。
我在zabbix里面把动作的主题配置成 故障: {EVENT.NAME}
其实{ALERT.SUBJECT} 相当于 动作的主题
谢谢您

现在返回的信息如下是正常的


故障: High memory utilization ( >70% for 5m)
触发时间：2023.02.22 15:47:23
主机名称：**********
 --- 
 OpenAI 砖家建议：
 1. 首先要排查是什么原因导致了内存占用过高，这里可以通过查看系统日志以及Zabbix监控结果来确定是什么样的活动导致了这样的结果。

2. 确定出问题原因之后，尝试对问题原因进行优化，比如增加系统资源、升级内存等，以降低内存占用率。

3. 如果优化措施没有起到效果，可以尝试重启服务器，以释放内存。

4. 如果内存使用持续高，可以增加内存容量或更换新的硬件。
